### ISSUE TITLE
analyzer dependency upgrade to 5.x

### ISSUE THREAD

**Issue by noinskit** [sysint64/icu_parser#3]
Could you please release a version with the analyzer dependency bumped to ^5.10.0 (or similar)?

Other packages already moved forward and it's problematic to use icu_parser e.g. with the current version of flutter_svg, due to conflicts in their dependencies.

**Comment by sysint64** [comment]
Sorry for the long response, published version `1.4.0` with minimum analyzer version `5.2.0`; Also wrote and example in tests.

**Comment by noinskit** [comment]
Great, thanks!
